/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activos;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;

import deprecated.ds_bd;

/**
 *
 * @author daveybtw
 */
public class SubestacionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ds_admin_user
     */
    ds_bd gestorBD = new ds_bd();
    ArrayList<JTextField> Components = new ArrayList<JTextField>();
    ControlSubestacion controlador = new ControlSubestacion();
    public SubestacionGUI() {
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(100, 30);
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        initComponents();
        Components.add(text_encargado);
        Components.add(text_ciudad);
        Components.add(text_direccion);
        changeBorders(Components);
        // ---------------------------------------------
        
        // ----------------------------------------------
    }
    
    public void changeBorders(ArrayList<JTextField> Componentes){
        for(int i = 0; i < Componentes.size(); i++){
            Componentes.get(i).setBorder(BorderFactory.createCompoundBorder(
            Componentes.get(i).getBorder(), 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_menu = new javax.swing.JPanel();
        left_footer = new javax.swing.JPanel();
        Cerrar_Sesion = new javax.swing.JLabel();
        left_header = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        left_options = new javax.swing.JPanel();
        registrar_usuarios = new javax.swing.JLabel();
        inicio_left = new javax.swing.JLabel();
        modificar_left = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        min_btn = new javax.swing.JLabel();
        cls_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_encargado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btn_registro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_menu.setBackground(new java.awt.Color(50, 55, 61));
        left_menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        left_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_footer.setBackground(new java.awt.Color(50, 55, 61));
        left_footer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        left_footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar_Sesion.setBackground(new java.awt.Color(254, 254, 254));
        Cerrar_Sesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cerrar_Sesion.setForeground(new java.awt.Color(254, 254, 254));
        Cerrar_Sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cerrar_Sesion.setText("Cerrar Sesion");
        Cerrar_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cerrar_SesionMouseExited(evt);
            }
        });
        left_footer.add(Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 20));

        left_menu.add(left_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 230, 20));

        left_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/avatar.png"))); // NOI18N
        left_header.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, -1));

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        left_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 180));
        left_header.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1100, 20));
        left_header.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        left_menu.add(left_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 180));

        left_options.setBackground(new java.awt.Color(50, 55, 61));
        left_options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar_usuarios.setForeground(new java.awt.Color(254, 254, 254));
        registrar_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar_usuarios.setText("Registrar usuarios");
        registrar_usuarios.setAlignmentX(0.6F);
        registrar_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar_usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrar_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrar_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrar_usuariosMouseExited(evt);
            }
        });
        left_options.add(registrar_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 30));

        inicio_left.setForeground(new java.awt.Color(254, 254, 254));
        inicio_left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_left.setText("Inicio");
        inicio_left.setAlignmentX(0.6F);
        inicio_left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio_left.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inicio_left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicio_leftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicio_leftMouseExited(evt);
            }
        });
        left_options.add(inicio_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 30));

        modificar_left.setForeground(new java.awt.Color(254, 254, 254));
        modificar_left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar_left.setText("Modificar usuarios");
        modificar_left.setAlignmentX(0.6F);
        modificar_left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar_left.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificar_left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificar_leftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificar_leftMouseExited(evt);
            }
        });
        left_options.add(modificar_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        left_menu.add(left_options, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 470));

        getContentPane().add(left_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 670));

        jPanel8.setBackground(new java.awt.Color(50, 55, 61));
        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_minimize.png"))); // NOI18N
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
        });
        jPanel8.add(min_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 20, 20));

        cls_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_close.png"))); // NOI18N
        cls_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cls_btnMouseClicked(evt);
            }
        });
        jPanel8.add(cls_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 20, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SiGE");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 20));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 20));

        content_panel.setBackground(java.awt.Color.white);
        content_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title.setText("Adicion de nuevas subestaciones de energia");
        content_panel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel3.setText("Documento del encargado");
        content_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        text_encargado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 300, 30));

        jLabel4.setText("Ciudad donde se encuentra la subestacion");
        content_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        text_ciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 300, 30));

        jLabel5.setText("Direccion donde se encuentra la subestacion");
        content_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        text_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 300, 30));

        jLabel6.setText("Estado de la subestacion");
        content_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        content_panel.add(combo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registrar subestacion");
        content_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, 30));

        btn_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button.png"))); // NOI18N
        btn_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registroMouseClicked(evt);
            }
        });
        content_panel.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 160, -1));

        getContentPane().add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 870, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_usuariosMouseEntered
        registrar_usuarios.setOpaque(true);
        registrar_usuarios.setBackground(new Color(2, 143, 224));// TODO add your handling code here:
    }//GEN-LAST:event_registrar_usuariosMouseEntered

    private void registrar_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_usuariosMouseExited
        registrar_usuarios.setOpaque(false);
        registrar_usuarios.setBackground(new Color(50,55,61));// TODO add your handling code here:
    }//GEN-LAST:event_registrar_usuariosMouseExited

    private void inicio_leftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_leftMouseEntered
        inicio_left.setOpaque(true);
        inicio_left.setBackground(new Color(2, 143, 224));// TODO add your handling code here:
    }//GEN-LAST:event_inicio_leftMouseEntered

    private void inicio_leftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_leftMouseExited
        inicio_left.setOpaque(false);
        inicio_left.setBackground(new Color(50,55,61));// TODO add your handling code here:
    }//GEN-LAST:event_inicio_leftMouseExited

    private void modificar_leftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_leftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_leftMouseEntered

    private void modificar_leftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_leftMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_leftMouseExited

    private void cls_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cls_btnMouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cls_btnMouseClicked

    private void Cerrar_SesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseExited
        Cerrar_Sesion.setOpaque(false);
        Cerrar_Sesion.setBackground(new Color(50,55,61));
        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar_SesionMouseExited

    private void Cerrar_SesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseEntered

        Cerrar_Sesion.setOpaque(true);
        Cerrar_Sesion.setBackground(new Color(2, 143, 224));
    }//GEN-LAST:event_Cerrar_SesionMouseEntered

    private void Cerrar_SesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar_SesionMouseClicked
        this.dispose();
    }//GEN-LAST:event_Cerrar_SesionMouseClicked

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_min_btnMouseClicked

    private void btn_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseClicked
        switch(controlador.createNewSubestacion(Components, text_encargado.getText(), text_ciudad.getText(), text_direccion.getText(), String.valueOf(combo_estado.getSelectedItem()))){
            case 0:
                JOptionPane.showMessageDialog(this, "Fallo la creacion de la nueva subestacion");
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Creacion de la subestacion completa");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Llene todos los campos e intente nuevamente");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "El campo 'Documento del encargado' debe ser llenado unicamente con numeros");
                break;
        }
    }//GEN-LAST:event_btn_registroMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubestacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubestacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubestacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubestacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubestacionGUI().setVisible(true);
            }
        });
    }
    
    public static class FrameDragListener extends MouseAdapter {

        private final JFrame frame;
        private Point mouseDownCompCoords = null;

        public FrameDragListener(JFrame frame) {
            this.frame = frame;
        }

        public void mouseReleased(MouseEvent e) {
            mouseDownCompCoords = null;
        }

        public void mousePressed(MouseEvent e) {
            mouseDownCompCoords = e.getPoint();
        }

        public void mouseDragged(MouseEvent e) {
            Point currCoords = e.getLocationOnScreen();
            frame.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar_Sesion;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel btn_registro;
    private javax.swing.JLabel cls_btn;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel inicio_left;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel left_footer;
    private javax.swing.JPanel left_header;
    private javax.swing.JPanel left_menu;
    private javax.swing.JPanel left_options;
    private javax.swing.JLabel min_btn;
    private javax.swing.JLabel modificar_left;
    private javax.swing.JLabel registrar_usuarios;
    private javax.swing.JTextField text_ciudad;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_encargado;
    // End of variables declaration//GEN-END:variables
}
