package activos;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author camilo
 */
public class SubestacionPanel extends javax.swing.JPanel {

    ArrayList<JTextField> Components = new ArrayList<JTextField>();
    ControlSubestacion controlador = new ControlSubestacion();

    /**
     * Creates new form SubestacionPanel
     */
    public SubestacionPanel() {
        initComponents();
        Components.add(text_encargado);
        Components.add(text_ciudad);
        Components.add(text_direccion);
        changeBorders(Components);
        initComponents();
    }
    public void lightMode() {
        FlatLightLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();
    }
    public void darkMode(){
        FlatDarkLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();

    }
    public void changeBorders(ArrayList<JTextField> Componentes){
        for(int i = 0; i < Componentes.size(); i++){
            Componentes.get(i).setBorder(BorderFactory.createCompoundBorder(
                    Componentes.get(i).getBorder(),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_encargado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        btn_registro = new javax.swing.JButton();

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        Title.setText("Adicion de nuevas subestaciones de energia");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel3.setText("Documento del encargado");

        text_encargado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Ciudad donde se encuentra la subestacion");

        text_ciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Direccion donde se encuentra la subestacion");

        text_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Estado de la subestacion");

        combo_estado.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btn_registro.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btn_registro.setText("Registrar Subestacion");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Title))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btn_registro))
                    .addComponent(text_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_encargado, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Title)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_encargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(text_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(text_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btn_registro)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed

        switch (controlador.createNewSubestacion(Components, String.valueOf(text_encargado.getText()), text_ciudad.getText(), text_direccion.getText(), String.valueOf(combo_estado.getSelectedItem()))) {
            case 0:
                JOptionPane.showMessageDialog(this, "Fallo la creacion de la nueva subestacion");
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Creacion de la subestacion completa");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Llene todos los campos e intente nuevamente");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "El campo 'Documento del encargado' debe ser llenado unicamente con numeros");
                break;
        }
    }//GEN-LAST:event_btn_registroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btn_registro;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField text_ciudad;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_encargado;
    // End of variables declaration//GEN-END:variables

}
