package activos;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author camilo
 */
public class SubestacionPanel extends javax.swing.JPanel {

    ArrayList<JTextField> Components = new ArrayList<JTextField>();
    ControlSubestacion controlador = new ControlSubestacion();

    /**
     * Creates new form SubestacionPanel
     */
    public SubestacionPanel() {
        initComponents();
        Components.add(text_encargado);
        Components.add(text_ciudad);
        Components.add(text_direccion);
        changeBorders(Components);
        initComponents();
    }
    public void lightMode() {
        FlatLightLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();
    }
    public void darkMode(){
        FlatDarkLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();

    }
    public void changeBorders(ArrayList<JTextField> Componentes){
        for(int i = 0; i < Componentes.size(); i++){
            Componentes.get(i).setBorder(BorderFactory.createCompoundBorder(
                    Componentes.get(i).getBorder(),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content_panel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_encargado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btn_registro = new javax.swing.JLabel();

        setLayout(null);

        content_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        content_panel.setLayout(null);

        Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title.setText("Adicion de nuevas subestaciones de energia");
        content_panel.add(Title);
        Title.setBounds(270, 40, 310, 17);

        jLabel3.setText("Documento del encargado");
        content_panel.add(jLabel3);
        jLabel3.setBounds(70, 90, 170, 17);

        text_encargado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_encargado);
        text_encargado.setBounds(70, 110, 300, 30);

        jLabel4.setText("Ciudad donde se encuentra la subestacion");
        content_panel.add(jLabel4);
        jLabel4.setBounds(70, 170, 272, 17);

        text_ciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_ciudad);
        text_ciudad.setBounds(70, 190, 300, 30);

        jLabel5.setText("Direccion donde se encuentra la subestacion");
        content_panel.add(jLabel5);
        jLabel5.setBounds(70, 260, 287, 17);

        text_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        content_panel.add(text_direccion);
        text_direccion.setBounds(70, 280, 300, 30);

        jLabel6.setText("Estado de la subestacion");
        content_panel.add(jLabel6);
        jLabel6.setBounds(470, 90, 160, 17);

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        content_panel.add(combo_estado);
        combo_estado.setBounds(470, 110, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registrar subestacion");
        content_panel.add(jLabel7);
        jLabel7.setBounds(370, 420, 140, 30);

        btn_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button.png"))); // NOI18N
        btn_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registroMouseClicked(evt);
            }
        });
        content_panel.add(btn_registro);
        btn_registro.setBounds(350, 410, 160, 48);

        add(content_panel);
        content_panel.setBounds(0, 0, 870, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseClicked
        switch (controlador.createNewSubestacion(Components, String.valueOf(text_encargado.getText()), text_ciudad.getText(), text_direccion.getText(), String.valueOf(combo_estado.getSelectedItem()))) {
            case 0:
                JOptionPane.showMessageDialog(this, "Fallo la creacion de la nueva subestacion");
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Creacion de la subestacion completa");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Llene todos los campos e intente nuevamente");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "El campo 'Documento del encargado' debe ser llenado unicamente con numeros");
                break;
        }
    }//GEN-LAST:event_btn_registroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel btn_registro;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField text_ciudad;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_encargado;
    // End of variables declaration//GEN-END:variables

}
