package sige.finance.Facturas;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatTableUI;

import sige.activos.subestacion.lista.ListaSubestaciones;
import sige.misc.TableCellListener;

public class FacturaPanel extends JPanel {
		private final FacturaModel modelo = new FacturaModel();
		private final GenerarFactura GeneraFactura = new GenerarFactura();
		private final DefaultTableModel mDefaultTableMoadel = new DefaultTableModel();
		private final TableRowSorter<TableModel> rowSorter;


		/**
		 * Creates new form FacturaPanel
		 */
		public FacturaPanel() {
			initComponents();
			construirTabla();
			rowSorter  = new TableRowSorter<>(tablaFacturas.getModel());
			TestTableSortFilter();
			FlatTableUI.createUI(tablaFacturas);
		}
		public void lightMode() {
			FlatLightLaf.install();
			FlatLaf.updateUI();
			this.revalidate();
			this.repaint();
		}
		public void darkMode(){
			FlatDarkLaf.install();
			FlatLaf.updateUI();
			this.revalidate();
			this.repaint();

		}
		public void TestTableSortFilter() {

			ListaSubestaciones.row(rowSorter, tablaFacturas, buscador);
		}
		/**
		 * This method is called from within the constructor to initialize the form.
		 * WARNING: Do NOT modify this code. The content of this method is always
		 * regenerated by the Form Editor.
		 */
		@SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jPanel3 = new JPanel();
	        jScrollPane1 = new JScrollPane();
	        tablaFacturas = new JTable();
	        buscador = new JTextField();
	        jLabel2 = new JLabel();
	        jButton1 = new JButton();
	        JButton2 = new JButton();

	        setLayout(new BorderLayout());

	        jPanel3.setBackground(Color.white);
	        jPanel3.setLayout(null);

	        jScrollPane1.setBackground(new Color(255, 255, 255));
	        jScrollPane1.setBorder(null);
	        jScrollPane1.setFocusable(false);

	        tablaFacturas.setModel(new DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        tablaFacturas.setFocusable(false);
	        tablaFacturas.setGridColor(new Color(255, 255, 255));
	        tablaFacturas.setRowHeight(25);
	        tablaFacturas.setSelectionBackground(new Color(2, 143, 224));
	        jScrollPane1.setViewportView(tablaFacturas);

	        jPanel3.add(jScrollPane1);
	        jScrollPane1.setBounds(50, 120, 780, 480);

	        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
	            public void keyPressed(KeyEvent evt) {
	                buscadorKeyPressed(evt);
	            }
	        });
	        jPanel3.add(buscador);
	        buscador.setBounds(90, 70, 580, 30);

	        jLabel2.setBackground(new Color(255, 255, 255));
	        jLabel2.setFont(new Font("Fira Code", 0, 14)); // NOI18N
	        jLabel2.setForeground(new Color(0, 0, 0));
	        jLabel2.setText("Buscador");
	        jPanel3.add(jLabel2);
	        jLabel2.setBounds(360, 40, 72, 18);

	        add(jPanel3, BorderLayout.CENTER);
	        jButton1.setText("Refrescar");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        JButton2.setText("Factura");
	        JButton2.addActionListener(new java.awt.event.ActionListener() {
	        	public void actionPerformed(ActionEvent evt) {
	        		JButton2ActionPerformed(evt);
	        	}
	        });

	        jPanel3.add(jButton1);
	        jButton1.setBounds(660, 70, 90, 30);
	        jPanel3.add(JButton2);
	        JButton2.setBounds(740, 70, 90, 30);
	    }// </editor-fold>//GEN-END:initComponents

		private void buscadorKeyPressed(KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed
		}//GEN-LAST:event_buscadorKeyPressed
	    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	        construirTabla();
	    }//GEN-LAST:event_jButton1ActionPerformed
	    private void JButton2ActionPerformed(ActionEvent evt){
	    	String code = JOptionPane.showInputDialog(null, "Ingresar contrato", "");
	    	GeneraFactura.VerifyInput(code);
	    }
		public void construirTabla() {
			String[] titlesInfo = new String[7];
			titlesInfo[0] = "ID";
			titlesInfo[1] = "Nombre";
			titlesInfo[2] = "Apellido";
			titlesInfo[3] = "Correo";
			titlesInfo[4] = "Contrato";
			titlesInfo[5] = "Fecha de Expedicion";
			titlesInfo[6] = "Fecha de vencimiento";
			mDefaultTableMoadel.setDataVector(modelo.obtenerMatrizData(), titlesInfo);
			tablaFacturas.setModel(mDefaultTableMoadel);
			tablaFacturas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
			tablaFacturas.getTableHeader().setOpaque(true);
			tablaFacturas.setRowHeight(25);
			tablaFacturas.setCellSelectionEnabled(false);
			 /*Action action = new AbstractAction() {
				public void actionPerformed(ActionEvent e) {
					TableCellListener tcl = (TableCellListener) e.getSource();
					modelo.updateData(tcl.getColumn(), (String) tcl.getNewValue(),
							(String) tablaFacturas.getModel().getValueAt(tcl.getRow(), 0));
					System.out.println("Row   : " + tcl.getRow());
					System.out.println("Column: " + tcl.getColumn());
					System.out.println("Old   : " + tcl.getOldValue());
					System.out.println("New   : " + tcl.getNewValue());
				}
			};

			TableCellListener tcl = new TableCellListener(tablaFacturas, action);*/
		}

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private JTextField buscador;
	    private JButton jButton1;
	    private JButton JButton2;
	    private JLabel jLabel2;
	    private JPanel jPanel3;
	    private JScrollPane jScrollPane1;
	    private JTable tablaFacturas;
	    // End of variables declaration//GEN-END:variables
}

