package activos.transformadores;

import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import activos.transformadores.lista.ModeloListaTran;
import db.JDBCConnection;

/**
 *
 * @author david
 */
public class TransformadorPanel extends javax.swing.JPanel {
	ArrayList<JTextField> Components = new ArrayList<JTextField>();
	private ControlTransformador control;
	private ModeloListaTran mod;
    /**
     * Creates new form TransformadorPanel
     */
    public TransformadorPanel(JDBCConnection DB) {
    	control = new ControlTransformador(DB);
    	mod = new ModeloListaTran(DB);
        initComponents();
        Components.add(serialTxt);
        Components.add(capacidadTxt);
        setComboOptions();
    }
    
    private void setComboOptions() {
    	String[] options = mod.getSubes().toArray(new String[0]);
    	comboSub.removeAllItems();
    	for (String s : options) {
    		comboSub.addItem(s);
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        serialLabel = new javax.swing.JLabel();
        serialTxt = new javax.swing.JTextField();
        capacidadLabel = new javax.swing.JLabel();
        capacidadTxt = new javax.swing.JTextField();
        subLabel = new javax.swing.JLabel();
        comboSub = new javax.swing.JComboBox<>();
        activoRadioBtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("SF Pro Rounded", 0, 18)); // NOI18N
        titleLabel.setText("Crear nuevo transformador");

        serialLabel.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        serialLabel.setText("Serial");

        serialTxt.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N

        capacidadLabel.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        capacidadLabel.setText("Capacidad (KWh)");

        capacidadTxt.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N

        subLabel.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        subLabel.setText("Subestación a la que pertenece");

        comboSub.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        comboSub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        activoRadioBtn.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        activoRadioBtn.setText("¿Activo?");
        activoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoRadioBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        saveBtn.setText("Guardar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serialLabel)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadLabel)
                    .addComponent(capacidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(subLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboSub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(activoRadioBtn))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addGap(371, 371, 371))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialLabel)
                    .addComponent(subLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(capacidadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activoRadioBtn)
                    .addComponent(capacidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(259, 259, 259))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoRadioBtnActionPerformed
    	
    }//GEN-LAST:event_activoRadioBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    	if (control.checkFields(Components)) {
    		HashMap<String, String> datos = new HashMap<String,String>();
    		
    		datos.put("capacidad", capacidadTxt.getText());
    		datos.put("serial", serialTxt.getText());
    		datos.put("id_subestacion", String.valueOf(comboSub.getSelectedItem()));
    		
    		String activo = activoRadioBtn.isSelected() ? "true" : "false";
    		datos.put("estado", activo);
    		
    		int result = control.attemptCrear(datos);
    		if (result == 0) {
    			JOptionPane.showMessageDialog(this, "Transformador añadido con éxito");
    		}
    		else if (result == -1) {
    			JOptionPane.showMessageDialog(this, "Inserte una capacidad coherente.","Advertencia",JOptionPane.WARNING_MESSAGE);
    		}
    		else if (result == -2) {
    			JOptionPane.showMessageDialog(this, "Error al conectarse con el servidor.", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    	else {
    		JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.");
    	}
    }//GEN-LAST:event_saveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activoRadioBtn;
    private javax.swing.JLabel capacidadLabel;
    private javax.swing.JTextField capacidadTxt;
    private javax.swing.JComboBox<String> comboSub;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
