package finance.pagoSucursal;

import java.io.File;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import user.User;

/**
 * Vista de la funcionalidad que permite a los clientes
 * realizar sus pagos en sucursales bancarias.
 * 
 */
public class VistaSucursal extends javax.swing.JPanel {
	private ControlSucursal control;
	private User loggedUser;
   
    
	
	public VistaSucursal(User user) {
		this.loggedUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();

        setPreferredSize(new java.awt.Dimension(858, 654));

        titleLabel.setFont(new java.awt.Font("Lucida Gr", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Pago en sucursales");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setText("Escoja un archivo a cargar:");

        fileChooser.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        fileChooser.setFileFilter(new FileNameExtensionFilter("Texto", ".txt"));
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
    	File bankFile = fileChooser.getSelectedFile();
    	if (bankFile != null) {
        	control = new ControlSucursal(bankFile, loggedUser.getUserID());
        	
        	int result = control.validateFile();
        	
        	if (result >=0) {
        		JOptionPane.showMessageDialog(
        				this, "Error en el archivo cargado. "
        						+ "Por favor abralo manualmente y revise "
        						+ "los contenidos desde la línea "+result+1+" hasta la "+result+4+".\n"
        						+ " Edite el archivo manualmente y vuelva a intentarlo.",
        						"Advertencia", JOptionPane.WARNING_MESSAGE 
        				);
        	} else {
        		JOptionPane.showMessageDialog(this, "Pagos registrados correctamente.");
        	}
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
