/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance;

import javax.swing.JOptionPane;

import user.User;

import java.util.*;

/**
 *
 * @author david
 */
public class RegistrarPagoGUI extends javax.swing.JPanel {
    private ControlRegistrarPago control;
    private HashMap<String, Object> datosContrato;
    private User loggedUser;

    /**
     * Creates new form RegistrarPagoGUI
     */
    public RegistrarPagoGUI(User usuario) {
        control = new ControlRegistrarPago();
        datosContrato = new HashMap<String, Object>();
        loggedUser = usuario;
        initComponents();
        infoContratoPanel.setVisible(false);
        pagarPanel.setVisible(false);
    }
    
    /**
     * Popula los JLabels de infoContratoPanel
     * con la información contenida en datosContrato.
     */
    private void populateInfoContrato() {
        clienteNombreLbl.setText(datosContrato.get("nombre").toString());
        dirTextLabel.setText(datosContrato.get("dir_instalacion").toString());
        deudaCantLabel.setText(datosContrato.get("deuda_actual").toString());
        estratoNumLbl.setText(datosContrato.get("estrato").toString());
        
        infoContratoPanel.setVisible(true);
    }
    
    private void showMessage(String title, String msg, int tipo) {
    	JOptionPane.showMessageDialog(this, msg, title, tipo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        contratoLabel = new javax.swing.JLabel();
        contratoTxt = new javax.swing.JTextField();
        consultarBtn = new javax.swing.JButton();
        infoContratoPanel = new javax.swing.JPanel();
        deudaLabel = new javax.swing.JLabel();
        deudaCantLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        estratoLabel = new javax.swing.JLabel();
        dirLabel = new javax.swing.JLabel();
        clienteNombreLbl = new javax.swing.JLabel();
        estratoNumLbl = new javax.swing.JLabel();
        dirTextLabel = new javax.swing.JLabel();
        pagarPanel = new javax.swing.JPanel();
        valorPagarTxt = new javax.swing.JTextField();
        valorPagarLabel = new javax.swing.JLabel();
        pagarBtn = new javax.swing.JButton();
        cancelarPagoBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(870, 670));

        tituloLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Registrar pago");

        contratoLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contratoLabel.setText("#Contrato");

        contratoTxt.setToolTipText("");
        contratoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoTxtActionPerformed(evt);
            }
        });

        consultarBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        consultarBtn.setText("Consultar");
        consultarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarBtnMouseClicked(evt);
            }
        });
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });

        infoContratoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        infoContratoPanel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        deudaLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        deudaLabel.setText("Deuda total:");

        deudaCantLabel.setText("0");

        clienteLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        clienteLabel.setText("Cliente:");

        estratoLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        estratoLabel.setText("Estrato:");

        dirLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        dirLabel.setText("Dirección:");

        clienteNombreLbl.setText("jLabel1");

        estratoNumLbl.setText("jLabel2");

        dirTextLabel.setText("jLabel3");

        javax.swing.GroupLayout infoContratoPanelLayout = new javax.swing.GroupLayout(infoContratoPanel);
        infoContratoPanel.setLayout(infoContratoPanelLayout);
        infoContratoPanelLayout.setHorizontalGroup(
            infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoContratoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoContratoPanelLayout.createSequentialGroup()
                        .addComponent(deudaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deudaCantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoContratoPanelLayout.createSequentialGroup()
                        .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteLabel)
                            .addComponent(estratoLabel)
                            .addComponent(dirLabel))
                        .addGap(36, 36, 36)
                        .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirTextLabel)
                            .addComponent(estratoNumLbl)
                            .addComponent(clienteNombreLbl))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoContratoPanelLayout.setVerticalGroup(
            infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoContratoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deudaLabel)
                    .addComponent(deudaCantLabel))
                .addGap(18, 18, 18)
                .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(clienteNombreLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estratoLabel)
                    .addComponent(estratoNumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoContratoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirLabel)
                    .addComponent(dirTextLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pagarPanel.setBackground(new java.awt.Color(255, 255, 255));

        valorPagarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPagarTxtActionPerformed(evt);
            }
        });

        valorPagarLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        valorPagarLabel.setText("Valor a pagar");

        pagarBtn.setBackground(new java.awt.Color(153, 255, 153));
        pagarBtn.setText("Efectuar pago");
        pagarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBtnActionPerformed(evt);
            }
        });

        cancelarPagoBtn.setBackground(new java.awt.Color(255, 102, 102));
        cancelarPagoBtn.setText("Cancelar");
        cancelarPagoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarPagoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPagoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagarPanelLayout = new javax.swing.GroupLayout(pagarPanel);
        pagarPanel.setLayout(pagarPanelLayout);
        pagarPanelLayout.setHorizontalGroup(
            pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagarPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarPagoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagarPanelLayout.createSequentialGroup()
                        .addComponent(valorPagarLabel)
                        .addGap(16, 16, 16)))
                .addGap(30, 30, 30)
                .addGroup(pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorPagarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagarBtn))
                .addGap(66, 66, 66))
        );
        pagarPanelLayout.setVerticalGroup(
            pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorPagarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPagarLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(pagarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPagoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(pagarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoContratoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contratoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contratoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloLabel)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contratoLabel)
                    .addComponent(contratoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(infoContratoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pagarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contratoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contratoTxtActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        // TODO add your handling code here:
    	String s = contratoTxt.getText();
        if (s.equals("")) {
            JOptionPane.showMessageDialog(pagarPanel, "Campo contrato debe estar lleno", "Advertencia", JOptionPane.WARNING_MESSAGE );
        }
        else {
            if (control.attemptConsultarContrato(contratoTxt.getText())) {
                datosContrato = control.getContrato();
                populateInfoContrato();
                pagarPanel.setVisible(true);
            } else {
            	JOptionPane.showMessageDialog(
            			pagarPanel, "El contrato "+s+" no existe.", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void valorPagarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPagarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPagarTxtActionPerformed

    private void pagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBtnActionPerformed
    	String montoAPagar = valorPagarTxt.getText();
    	if (!montoAPagar.isEmpty() && montoAPagar.chars().allMatch( Character::isDigit )) {
    		float monto = Float.parseFloat(montoAPagar);
    		
    		if (monto > 0.0) {
    			
    			if (control.attemptPago(Integer.parseInt(contratoTxt.getText()), monto, loggedUser.getUserID())) {
    				showMessage("Éxito", "Pago realizado con éxito", JOptionPane.INFORMATION_MESSAGE);
    				pagarPanel.setVisible(false);
    		        infoContratoPanel.setVisible(false);
    				
    			} else {
    				showMessage("Error", "Ha ocurrido un error, inténtelo de nuevo.", JOptionPane.ERROR_MESSAGE);
    			}
    			
    		} else {
    			showMessage("Monto inválido", "Introduza un monto válido", JOptionPane.WARNING_MESSAGE);
    		}
    	}
    	else {
    		showMessage("Campo inválido", "Introduza un valor válido", JOptionPane.WARNING_MESSAGE);
    	}
    }//GEN-LAST:event_pagarBtnActionPerformed

    private void consultarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_consultarBtnMouseClicked

    private void cancelarPagoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPagoBtnActionPerformed
        pagarPanel.setVisible(false);
        infoContratoPanel.setVisible(false);
    }//GEN-LAST:event_cancelarPagoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarPagoBtn;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel clienteNombreLbl;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JLabel contratoLabel;
    private javax.swing.JTextField contratoTxt;
    private javax.swing.JLabel deudaCantLabel;
    private javax.swing.JLabel deudaLabel;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JLabel dirTextLabel;
    private javax.swing.JLabel estratoLabel;
    private javax.swing.JLabel estratoNumLbl;
    private javax.swing.JPanel infoContratoPanel;
    private javax.swing.JButton pagarBtn;
    private javax.swing.JPanel pagarPanel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel valorPagarLabel;
    private javax.swing.JTextField valorPagarTxt;
    // End of variables declaration//GEN-END:variables
}
