package sige.activos.subestacion;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;

import sige.db.JDBCConnection;

import java.util.*;

import javax.swing.*;

/**
 *
 * @author camilo
 */
public class SubestacionPanel extends JPanel {

    ArrayList<JTextField> Components = new ArrayList<JTextField>();
    ControlSubestacion controlador;

    /**
     * Creates new form SubestacionPanel
     */
    public SubestacionPanel(JDBCConnection conn) {
    	controlador = new ControlSubestacion(conn);
        initComponents();
        Components.add(text_encargado);
        Components.add(text_ciudad);
        Components.add(text_direccion);
        Components.add(nombreTxt);
        changeBorders(Components);
        //initComponents();
    }
    public void lightMode() {
        FlatLightLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();
    }
    public void darkMode(){
        FlatDarkLaf.install();
        FlatLaf.updateUI();
        this.revalidate();
        this.repaint();

    }
    public void changeBorders(ArrayList<JTextField> Componentes){
        for(int i = 0; i < Componentes.size(); i++){
            Componentes.get(i).setBorder(BorderFactory.createCompoundBorder(
                    Componentes.get(i).getBorder(),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new JLabel();
        jLabel3 = new JLabel();
        text_encargado = new JTextField();
        jLabel4 = new JLabel();
        text_ciudad = new JTextField();
        jLabel5 = new JLabel();
        text_direccion = new JTextField();
        jLabel6 = new JLabel();
        combo_estado = new JComboBox<>();
        btn_registro = new JButton();
        nombreTxt = new JTextField();
        nombreLabel = new JLabel();

        setLayout(null);

        Title.setFont(new java.awt.Font("SF Pro Rounded", 1, 18)); // NOI18N
        Title.setText("Adición de nuevas subestaciones de energía");
        add(Title);
        Title.setBounds(247, 34, 370, 23);

        jLabel3.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        jLabel3.setText("Documento del encargado");
        add(jLabel3);
        jLabel3.setBounds(114, 86, 153, 18);

        text_encargado.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        text_encargado.setBorder(BorderFactory.createEtchedBorder());
        add(text_encargado);
        text_encargado.setBounds(114, 106, 321, 30);

        jLabel4.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad donde se encuentra la subestacion");
        add(jLabel4);
        jLabel4.setBounds(114, 166, 247, 18);

        text_ciudad.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        text_ciudad.setBorder(BorderFactory.createEtchedBorder());
        add(text_ciudad);
        text_ciudad.setBounds(114, 189, 321, 30);

        jLabel5.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        jLabel5.setText("Direccion donde se encuentra la subestacion");
        add(jLabel5);
        jLabel5.setBounds(114, 259, 259, 18);

        text_direccion.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        text_direccion.setBorder(BorderFactory.createEtchedBorder());
        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });
        add(text_direccion);
        text_direccion.setBounds(114, 281, 330, 30);

        jLabel6.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        jLabel6.setText("Estado de la subestacion");
        add(jLabel6);
        jLabel6.setBounds(515, 84, 146, 18);

        combo_estado.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        combo_estado.setModel(new DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        add(combo_estado);
        combo_estado.setBounds(515, 106, 240, 30);

        btn_registro.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        btn_registro.setText("Registrar Subestación");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        add(btn_registro);
        btn_registro.setBounds(359, 389, 180, 28);

        nombreTxt.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        add(nombreTxt);
        nombreTxt.setBounds(515, 188, 257, 30);

        nombreLabel.setFont(new java.awt.Font("SF Pro Rounded", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre descriptivo");
        add(nombreLabel);
        nombreLabel.setBounds(515, 168, 206, 18);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed


    	String[] datos = {
    			text_encargado.getText(),
    			text_ciudad.getText(),
    			text_direccion.getText(),
    			String.valueOf(combo_estado.getSelectedItem()),
    			nombreTxt.getText()
    	};

        switch (controlador.createNewSubestacion(Components, datos)) {
            case 0:
                JOptionPane.showMessageDialog(this, "Fallo la creacion de la nueva subestacion");
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Creacion de la subestacion completa");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Llene todos los campos e intente nuevamente");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "El campo 'Documento del encargado' debe ser llenado unicamente con numeros");
                break;
        }
    }//GEN-LAST:event_btn_registroActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel Title;
    private JButton btn_registro;
    private JComboBox<String> combo_estado;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel nombreLabel;
    private JTextField nombreTxt;
    private JTextField text_ciudad;
    private JTextField text_direccion;
    private JTextField text_encargado;
    // End of variables declaration//GEN-END:variables

}
