/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance.contratos;

import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import misc.TableCellListener;

/**
 *
 * @author user
 */
public class ConsultaPanelContratos extends javax.swing.JPanel {
    
    private final ConsultaModeloContratos modelo = new ConsultaModeloContratos();
    private final DefaultTableModel mDefaultTableMoadelCliente = new DefaultTableModel();
    private final TableRowSorter<TableModel> rowSorterCliente;
    /**
     * Creates new form ConsulaPanelContratos
     */
    public ConsultaPanelContratos() {
        initComponents();
        construirTabla();
	rowSorterCliente  = new TableRowSorter<>(jTable1.getModel());
        TestTableSortFilter();
    }
    
    public void TestTableSortFilter() {

	jTable1.setRowSorter(rowSorterCliente);
	buscador.getDocument().addDocumentListener(new DocumentListener(){

		@Override
		public void insertUpdate(DocumentEvent e) {
			String text = buscador.getText();

			if (text.trim().length() == 0) {
				rowSorterCliente.setRowFilter(null);
			} else {
				rowSorterCliente.setRowFilter(RowFilter.regexFilter("(?i)" + text));
			}
		}

		@Override
		public void removeUpdate(DocumentEvent e) {
			String text = buscador.getText();

			if (text.trim().length() == 0) {
				rowSorterCliente.setRowFilter(null);
			} else {
				rowSorterCliente.setRowFilter(RowFilter.regexFilter("(?i)" + text));
			}
		}

		@Override
		public void changedUpdate(DocumentEvent e) {
			throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
		}

	});
    }
    public void noModificable(){
        JOptionPane.showMessageDialog(this, "Este campo no es modificable","Error al tratar de modificar el campo",1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setBackground(new java.awt.Color(255, 153, 153));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buscador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void construirTabla() {
	String[] titlesInfo = new String[6];
        titlesInfo[0] = "Numero de Documento del cliente";
	titlesInfo[1] = "Activo";
        titlesInfo[2] = "Direccion de la instalacion";
	titlesInfo[3] = "Deuda Actual";
	titlesInfo[4] = "Fecha de Corte";
	titlesInfo[5] = "Estrato";
	mDefaultTableMoadelCliente.setDataVector(modelo.obtenerMatrizData(), titlesInfo);
	jTable1.setModel(mDefaultTableMoadelCliente);
	jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
	jTable1.getTableHeader().setOpaque(true);
	jTable1.setRowHeight(25);
	jTable1.setCellSelectionEnabled(true);
	Action action = new AbstractAction() {
		public void actionPerformed(ActionEvent e) 
                {
			TableCellListener tcl = (TableCellListener) e.getSource();
                        if(tcl.getColumn() ==0){
                            noModificable();
                            jTable1.setValueAt(tcl.getOldValue(), tcl.getRow(), tcl.getColumn());
                        }
                        else{
                            modelo.updateData(tcl.getColumn(), (String) tcl.getNewValue(),
					(String) jTable1.getModel().getValueAt(tcl.getRow(), 0));
			System.out.println("Row   : " + tcl.getRow());
			System.out.println("Column: " + tcl.getColumn());
			System.out.println("Old   : " + tcl.getOldValue());
			System.out.println("New   : " + tcl.getNewValue());
                        }
		}
	};

	TableCellListener tcl = new TableCellListener(jTable1, action);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
