
package finance.clientes;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class RegisterPanelCliente extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 1L;
    private HashMap<String, String> datos = new HashMap<String, String>();
    private ControlRegisterCliente control;
	
    private EscuchaMouse escuchaM = new EscuchaMouse();
    /**
     * Creates new form RegisterPanelCliente
     */
    public RegisterPanelCliente() 
    {   
        control = new ControlRegisterCliente();
        initComponents();
    }
    public void valoresVacios(){
        JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados correctamente");
    }
    
    public void wrongTipoCliente()
    {
        JOptionPane.showMessageDialog(this, "El campo 'tipo de cliente' debe ser llenado unicamente con numeros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Apellido2Txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        tipoClienteCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        documentoTxt = new javax.swing.JTextField();
        primerApellidoTxt = new javax.swing.JTextField();
        tipoDocCombo = new javax.swing.JComboBox<>();

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, -1, -1));

        tituloLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tituloLabel.setText("Registro de nuevos clientes");
        jPanel3.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Primer apellido del cliente");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Tipo de cliente");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        Apellido2Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(Apellido2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 240, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Correo");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Nombre del cliente");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 240, 30));

        correoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        correoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTxtActionPerformed(evt);
            }
        });
        jPanel3.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 240, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Tipo de Documento");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Segundo apellido del cliente");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, 20));

        registerLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        registerLabel.setText("Registrar cliente");
        jPanel3.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        registerBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        registerBtn.setForeground(java.awt.Color.darkGray);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel3.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 160, 50));
        registerBtn.addMouseListener(escuchaM);

        tipoClienteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Corporativo" }));
        tipoClienteCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteComboActionPerformed(evt);
            }
        });
        jPanel3.add(tipoClienteCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 240, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Numero de documento");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        documentoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        documentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTxtActionPerformed(evt);
            }
        });
        jPanel3.add(documentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 240, 30));

        primerApellidoTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(primerApellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 30));

        tipoDocCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PA", "RC", "AS", "MS" }));
        tipoDocCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDocComboActionPerformed(evt);
            }
        });
        jPanel3.add(tipoDocCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 240, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registerBtnActionPerformed

    private void tipoClienteComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoClienteComboActionPerformed

    private void documentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTxtActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void tipoDocComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDocComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDocComboActionPerformed
    private void getFields() {
        datos.put("tipo_cliente", String.valueOf(tipoClienteCombo.getSelectedItem()));
    	datos.put("num_documento", documentoTxt.getText());
        datos.put("tipo_documento", String.valueOf(tipoDocCombo.getSelectedItem()));
    	datos.put("primer_nombre", jTextField3.getText());
    	datos.put("primer_apellido", primerApellidoTxt.getText());
        datos.put("segundo_apellido", Apellido2Txt.getText());
    	datos.put("email", correoTxt.getText() );
    }
    private class EscuchaMouse implements MouseListener 
    {
		public void mouseClicked(MouseEvent arg0) 
                {
			getFields();
	        if (control.datosCompletos(datos)) 
                {

	        	if (control.writeData(datos) > 0) 
                        {
	        		JOptionPane.showMessageDialog(null, "Cliente nuevo registrado exitosamente.");
	        	}
	        	else 
                        {
	        		JOptionPane.showMessageDialog(
	        				null, "Error guardando la información.", 
	        				"Error", JOptionPane.ERROR_MESSAGE);
	        	}
	        } 
                else 
                {
	        	valoresVacios();
	        }
		}

		@Override
		public void mouseEntered(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseExited(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mousePressed(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseReleased(MouseEvent arg0) {
			// TODO Auto-generated method stub
			
		}
    	
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido2Txt;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField documentoTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField primerApellidoTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> tipoClienteCombo;
    private javax.swing.JComboBox<String> tipoDocCombo;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
