package sige.user.consulta;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatTableUI;
import sige.activos.subestacion.lista.ListaSubestaciones;
import sige.misc.TableCellListener;

/**
 * Vista del componente de Consulta de Usuarios
 * 
 * @author camilo
 */
public class ConsultaPanel extends JPanel {
	private final ConsultaModelo modelo = new ConsultaModelo();
	private final DefaultTableModel mDefaultTableMoadel = new DefaultTableModel();
	private final TableRowSorter<TableModel> rowSorter;


	/**
	 * Creates new form ConsultaPanel
	 */
	public ConsultaPanel() {
		initComponents();
		construirTabla();
		rowSorter  = new TableRowSorter<>(tablaUsuarios.getModel());
		TestTableSortFilter();
		FlatTableUI.createUI(tablaUsuarios);
	}
	public void lightMode() {
		FlatLightLaf.install();
		FlatLaf.updateUI();
		this.revalidate();
		this.repaint();
	}
	public void darkMode(){
		FlatDarkLaf.install();
		FlatLaf.updateUI();
		this.revalidate();
		this.repaint();

	}

	public void TestTableSortFilter() {

        ListaSubestaciones.row(rowSorter, tablaUsuarios, buscador);
    }
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new JTabbedPane();
        jPanel3 = new JPanel();
        jScrollPane1 = new JScrollPane();
        tablaUsuarios = new JTable();
        buscador = new JTextField();
        jLabel2 = new JLabel();
        jButtonActualizar = new JButton();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        fieldUserId = new JTextField();
        jLabel4 = new JLabel();
        jPasswordField1 = new JPasswordField();
        buttonPassword = new JButton();

        setLayout(new CardLayout());

        jPanel3.setLayout(null);

        jScrollPane1.setBackground(UIManager.getDefaults().getColor("Table.background"));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);

        tablaUsuarios.setBackground(UIManager.getDefaults().getColor("Panel.background"));
        tablaUsuarios.setBorder(new javax.swing.border.MatteBorder(null));
        tablaUsuarios.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.setFocusable(false);
        tablaUsuarios.setOpaque(false);
        tablaUsuarios.setRowHeight(25);
        tablaUsuarios.setSelectionBackground(UIManager.getDefaults().getColor("Table.selectionBackground"));
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 780, 480);

        buscador.setFont(new Font("SF Pro Rounded", 0, 14)); // NOI18N
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                buscadorKeyPressed(evt);
            }
        });
        jPanel3.add(buscador);
        buscador.setBounds(90, 70, 670, 30);

        jLabel2.setBackground(UIManager.getDefaults().getColor("TextField.background"));
        jLabel2.setFont(new Font("SF Pro Rounded", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Buscador");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(360, 40, 76, 24);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonActualizar);
        jButtonActualizar.setBounds(770, 80, 90, 23);

        jTabbedPane1.addTab("Lista de Usuarios", jPanel3);

        jPanel1.setLayout(null);

        jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cambiar contraseña");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 220, 40);

        jScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para cambiar la contraseña de un usuario digite el id y la nueva contraseña que desea para el mismo.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(180, 80, 500, 90);

        jLabel3.setText("ID");
        jPanel2.add(jLabel3);

        fieldUserId.setColumns(5);
        fieldUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                fieldUserIdActionPerformed(evt);
            }
        });
        jPanel2.add(fieldUserId);

        jLabel4.setText("Nueva Contraseña");
        jPanel2.add(jLabel4);

        jPasswordField1.setColumns(15);
        jPanel2.add(jPasswordField1);

        buttonPassword.setText("Aplicar");
        buttonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(buttonPassword);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(140, 230, 550, 170);

        jTabbedPane1.addTab("Cambiar contraseña", jPanel1);

        add(jTabbedPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

	private void buscadorKeyPressed(KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed
	}//GEN-LAST:event_buscadorKeyPressed

    private void fieldUserIdActionPerformed(ActionEvent evt) {//GEN-FIRST:event_fieldUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserIdActionPerformed

    private void buttonPasswordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonPasswordActionPerformed
	    modelo.updateData(6, String.valueOf(jPasswordField1.getPassword()),fieldUserId.getText());

        JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente");
    }//GEN-LAST:event_buttonPasswordActionPerformed

    private void jButtonActualizarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        construirTabla();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

	public void construirTabla() {
		String[] titlesInfo = new String[6];
		titlesInfo[0] = "Cedula";
		titlesInfo[1] = "Nombre";
		titlesInfo[2] = "Apellido";
		titlesInfo[3] = "Correo";
		titlesInfo[4] = "Activo";
		titlesInfo[5] = "Rol ID";
		mDefaultTableMoadel.setDataVector(modelo.obtenerMatrizData(), titlesInfo);
		tablaUsuarios.setModel(mDefaultTableMoadel);
		tablaUsuarios.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
		tablaUsuarios.getTableHeader().setOpaque(true);
		tablaUsuarios.setRowHeight(25);
		tablaUsuarios.setCellSelectionEnabled(true);
		Action action = new AbstractAction() {
			public void actionPerformed(ActionEvent e) {
				TableCellListener tcl = (TableCellListener) e.getSource();
				modelo.updateData(tcl.getColumn(), (String) tcl.getNewValue(),
						(String) tablaUsuarios.getModel().getValueAt(tcl.getRow(), 0));
				System.out.println("Row   : " + tcl.getRow());
				System.out.println("Column: " + tcl.getColumn());
				System.out.println("Old   : " + tcl.getOldValue());
				System.out.println("New   : " + tcl.getNewValue());
			}
		};

		TableCellListener tcl = new TableCellListener(tablaUsuarios, action);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField buscador;
    private JButton buttonPassword;
    private JTextField fieldUserId;
    private JButton jButtonActualizar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPasswordField jPasswordField1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTabbedPane jTabbedPane1;
    private JTextArea jTextArea1;
    private JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
